/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfaces.Vista;

import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.interfaces.Modelo.UsuarioPrueba;
import controlador.ControladorIniciodeSesion;
import static java.awt.Color.black;
import javax.swing.JOptionPane;

/**
 *
 * @author driss
 */
public class Login extends javax.swing.JFrame { //EXTRA, Interfaz del login

    /**
     * Creates new form Login
     */
    
    UsuarioPrueba user = new UsuarioPrueba(); //Iniciamos la clase que manejará las credenciales
    ControladorIniciodeSesion ctrl = new ControladorIniciodeSesion(user);//El controlador que recibirá la clase usuarios para
    //poder verificarlos
    
    
    public Login() {
        initComponents();
        initStyles();//Aplicamos los estilos con el FlatLaf
        setLocationRelativeTo(null);//Centrar la interfaz de Login
    }
    
    public void initStyles(){
        botonIniciar.putClientProperty( "JButton.buttonType", "roundRect" );
        botonIniciar.putClientProperty( "FlatLaf.styleClass", "h4" );
        seleccionRol.putClientProperty("FlatLaf.styleClass", "h4");
        seleccionRol.putClientProperty( "JComponent.roundRect", true );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        HeaderImage = new javax.swing.JLabel();
        LogoContainer = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        PanelCred = new javax.swing.JPanel();
        seleccionRol = new javax.swing.JComboBox<>();
        separacion1 = new javax.swing.JPanel();
        separacion2 = new javax.swing.JPanel();
        separacion3 = new javax.swing.JPanel();
        botonIniciar = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Body.setBackground(new java.awt.Color(194, 179, 177));
        Body.setMaximumSize(new java.awt.Dimension(1389, 653));
        Body.setMinimumSize(new java.awt.Dimension(1389, 653));

        Header.setBackground(new java.awt.Color(255, 250, 240));
        Header.setMaximumSize(new java.awt.Dimension(1081, 237));
        Header.setMinimumSize(new java.awt.Dimension(1081, 237));

        HeaderImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Header.png"))); // NOI18N

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LogoContainer.setBackground(new java.awt.Color(247, 245, 240));
        LogoContainer.setMaximumSize(new java.awt.Dimension(522, 420));
        LogoContainer.setMinimumSize(new java.awt.Dimension(522, 420));

        Logo.setBackground(new java.awt.Color(255, 250, 240));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoLogin.png"))); // NOI18N

        javax.swing.GroupLayout LogoContainerLayout = new javax.swing.GroupLayout(LogoContainer);
        LogoContainer.setLayout(LogoContainerLayout);
        LogoContainerLayout.setHorizontalGroup(
            LogoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoContainerLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(Logo)
                .addGap(29, 29, 29))
        );
        LogoContainerLayout.setVerticalGroup(
            LogoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoContainerLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(Logo)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        PanelCred.setBackground(new java.awt.Color(217, 220, 237));
        PanelCred.setMaximumSize(new java.awt.Dimension(561, 318));
        PanelCred.setMinimumSize(new java.awt.Dimension(561, 318));
        PanelCred.setPreferredSize(new java.awt.Dimension(561, 318));

        seleccionRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));

        separacion1.setPreferredSize(new java.awt.Dimension(500, 2));

        javax.swing.GroupLayout separacion1Layout = new javax.swing.GroupLayout(separacion1);
        separacion1.setLayout(separacion1Layout);
        separacion1Layout.setHorizontalGroup(
            separacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        separacion1Layout.setVerticalGroup(
            separacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        separacion2.setPreferredSize(new java.awt.Dimension(500, 2));

        javax.swing.GroupLayout separacion2Layout = new javax.swing.GroupLayout(separacion2);
        separacion2.setLayout(separacion2Layout);
        separacion2Layout.setHorizontalGroup(
            separacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        separacion2Layout.setVerticalGroup(
            separacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        separacion3.setPreferredSize(new java.awt.Dimension(500, 2));

        javax.swing.GroupLayout separacion3Layout = new javax.swing.GroupLayout(separacion3);
        separacion3.setLayout(separacion3Layout);
        separacion3Layout.setHorizontalGroup(
            separacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        separacion3Layout.setVerticalGroup(
            separacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        botonIniciar.setText("Confirmar");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });

        usuario.setForeground(new java.awt.Color(204, 204, 204));
        usuario.setText("Usuario");
        usuario.setMaximumSize(new java.awt.Dimension(64, 22));
        usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioFocusGained(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        passField.setMaximumSize(new java.awt.Dimension(64, 22));

        javax.swing.GroupLayout PanelCredLayout = new javax.swing.GroupLayout(PanelCred);
        PanelCred.setLayout(PanelCredLayout);
        PanelCredLayout.setHorizontalGroup(
            PanelCredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCredLayout.createSequentialGroup()
                .addGroup(PanelCredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCredLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelCredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passField, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .addComponent(separacion1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .addComponent(separacion2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .addComponent(separacion3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .addComponent(usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelCredLayout.createSequentialGroup()
                                .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))
                    .addGroup(PanelCredLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(seleccionRol, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(5, Short.MAX_VALUE))
        );
        PanelCredLayout.setVerticalGroup(
            PanelCredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCredLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(seleccionRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonIniciar)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelCred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(PanelCred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(LogoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        // TODO add your handling code here:
        String user = usuario.getText();
        String pass = new String(passField.getPassword());
        String rol  = seleccionRol.getSelectedItem().toString();
        boolean comprobador = ctrl.autenticar(user, pass, rol);// Se usa el metodo autenticar del controlador 
        //para comprobar si el input del usuario es el mismo que el de la clase Usuario que creamos
        
        if (comprobador) { //Si el inicio de sesion es correcto
            JOptionPane.showMessageDialog(this, "Inicio de sesión correcto"); //Notificacion
            Vista vistaPrincipal = new Vista(rol); //Se abre la vista con el rol que se selecciono
            vistaPrincipal.setVisible(true);
            this.dispose();//Se cierra el login
        } else {//Si no
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas"); //Aviso al usuario
            usuario.setText("Usuario");
            passField.setText("");//Reseteo de los Fields
        }
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usuarioActionPerformed

    private void usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusGained
        // TODO add your handling code here:
        usuario.setText("");
        usuario.setForeground(black);
    }//GEN-LAST:event_usuarioFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel HeaderImage;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel LogoContainer;
    private javax.swing.JPanel PanelCred;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JPasswordField passField;
    private javax.swing.JComboBox<String> seleccionRol;
    private javax.swing.JPanel separacion1;
    private javax.swing.JPanel separacion2;
    private javax.swing.JPanel separacion3;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
